services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: cakestore
      POSTGRES_USER: cakestore
      POSTGRES_PASSWORD: cakestore
    volumes:
      - "db:/var/lib/postgresql/data"


volumes:
  db:

