# Generated by Django 4.1.5 on 2025-02-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="orders/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(default="Created", max_length=10),
        ),
    ]
